add_newline = false

format = "$character"
right_format = "$directory$git_branch$git_status"

[character]
success_symbol = "[λ](#9300c0)"
error_symbol = "[λ](red)"

[directory]
truncation_length = 1
truncate_to_repo = false
format = "[$path]($style) "

[git_branch]
format = "[$symbol$branch]($style) "

[git_status]
format = "([$ahead_behind$ahead_count$behind_count]($style) )"
